# Generated by Django 4.1.7 on 2023-03-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/%Y/%m/%d')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
