# Generated by Django 4.1.7 on 2023-03-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_rename_designation_profile_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Mobile_no',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
