# Generated by Django 4.1.7 on 2023-03-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0004_profile_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
