# Generated by Django 4.1.6 on 2023-03-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0005_alter_profile_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='details',
        ),
        migrations.AddField(
            model_name='profile',
            name='Description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='item',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
